import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "../provider/AuthProvider";
import { googleSans, notoSansJP } from "@/lib/font";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            style={{ height: "100%" }}
            className={`${googleSans.variable} ${notoSansJP.variable} antialiased`}
        >
            <body style={{ height: "100%" }}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
